/**
 * POST /marketing/email-preferences - Update marketing email consent
 *
 * Two supported modes:
 *
 * 1) Authenticated (account-page toggle):
 *    - User must be logged in.
 *    - settings.action = 'opt-in' | 'opt-out'.
 *    - Writes canonical consent.marketing to user doc.
 *    - Hits BOTH SendGrid + Beehiiv via the email library (one source of truth).
 *
 * 2) Anonymous (HMAC unsubscribe link from email footer):
 *    - No login. settings.email + settings.asmId + settings.sig + settings.action.
 *    - HMAC validates the link was generated by us.
 *    - Hits SendGrid ASM directly (legacy behavior — preserves existing one-click unsub).
 *    - Also writes canonical consent.marketing to user doc when email maps to a user.
 */
const fetch = require('wonderful-fetch');
const crypto = require('crypto');

const RATE_LIMIT = 5;

module.exports = async ({ assistant, Manager, user, settings, analytics }) => {

  // --- AUTHENTICATED MODE ---
  if (user.authenticated) {
    return handleAuthenticated({ assistant, Manager, user, settings, analytics });
  }

  // --- ANONYMOUS HMAC MODE ---
  return handleAnonymous({ assistant, Manager, settings, analytics });
};

/**
 * Authenticated user toggling marketing on/off from the account page.
 */
async function handleAuthenticated({ assistant, Manager, user, settings, analytics }) {
  const { admin } = Manager.libraries;
  const action = settings.action;

  if (action !== 'subscribe' && action !== 'unsubscribe') {
    return assistant.respond('Invalid action — must be "subscribe" or "unsubscribe"', { code: 400 });
  }

  // Rate-limit per-user (defense against accidental toggling spam)
  const usage = await Manager.Usage().init(assistant);
  const currentUsage = usage.getUsage('email-preferences');
  if (currentUsage >= RATE_LIMIT) {
    return assistant.respond('Rate limit exceeded', { code: 429 });
  }
  usage.increment('email-preferences');
  await usage.update();

  const uid = user.auth.uid;
  const email = user.auth.email;
  const ip = assistant.request.geolocation?.ip || null;
  const timestamp = assistant.meta.startTime.timestamp;
  const timestampUNIX = assistant.meta.startTime.timestampUNIX;

  // Build the consent.marketing mutation
  const marketingPatch = action === 'subscribe'
    ? {
      status: 'granted',
      grantedAt: { timestamp, timestampUNIX, source: 'account', ip, text: null },
      // Leave revokedAt untouched — informational record of most recent revoke
    }
    : {
      status: 'revoked',
      revokedAt: { timestamp, timestampUNIX, source: 'account', ip, text: null },
      // Leave grantedAt untouched — informational record of original grant
    };

  await admin.firestore().doc(`users/${uid}`).set({
    consent: { marketing: marketingPatch },
    metadata: Manager.Metadata().set({ tag: 'marketing/email-preferences' }),
  }, { merge: true });

  assistant.log(`email-preferences (auth): ${uid} → ${action}`);

  // Skip provider calls in test mode unless extended mode is on
  const shouldCallExternalAPIs = !assistant.isTesting() || process.env.TEST_EXTENDED_MODE;

  if (shouldCallExternalAPIs) {
    const mailer = Manager.Email(assistant);

    try {
      if (action === 'unsubscribe') {
        await mailer.remove(email);
      } else {
        await mailer.sync(uid);
      }
    } catch (e) {
      assistant.error(`email-preferences (auth) provider sync failed:`, e);
      // Doc is already updated — provider sync is best-effort. Don't fail the request.
    }
  } else {
    assistant.log('email-preferences (auth): Skipping provider calls (BEM_TESTING=true)');
  }

  analytics.event('marketing/email-preferences', { action, mode: 'authenticated' });

  return assistant.respond({ success: true, action });
}

/**
 * Anonymous HMAC unsubscribe link (preserves existing email-footer one-click flow).
 */
async function handleAnonymous({ assistant, Manager, settings, analytics }) {
  const { admin } = Manager.libraries;

  const email = (settings.email || '').trim().toLowerCase();
  const asmId = parseInt(settings.asmId, 10);
  const action = settings.action || 'unsubscribe';

  // Validate inputs
  if (!email) {
    return assistant.respond('Email is required', { code: 400 });
  }

  const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
  if (!emailRegex.test(email)) {
    return assistant.respond('Invalid email format', { code: 400 });
  }

  if (!asmId || isNaN(asmId)) {
    return assistant.respond('ASM group ID is required', { code: 400 });
  }

  if (action !== 'subscribe' && action !== 'unsubscribe') {
    return assistant.respond('Invalid action', { code: 400 });
  }

  // HMAC validation (proves we generated this link)
  const expectedSig = crypto.createHmac('sha256', process.env.UNSUBSCRIBE_HMAC_KEY).update(email).digest('hex');
  if (settings.sig !== expectedSig) {
    return assistant.respond('Invalid signature', { code: 403 });
  }

  // IP rate limiting (anonymous flow — unauthenticated firestore storage)
  const usage = await Manager.Usage().init(assistant, {
    unauthenticatedMode: 'firestore',
    key: assistant.request.geolocation.ip,
  });
  const currentUsage = usage.getUsage('email-preferences');
  if (currentUsage >= RATE_LIMIT) {
    return assistant.respond('Rate limit exceeded', { code: 429 });
  }
  usage.increment('email-preferences');
  await usage.update();

  // Mirror to the user doc if this email maps to a user (best-effort, silent on miss)
  await mirrorAnonymousToUserDoc({ assistant, Manager, email, action });

  // Call SendGrid ASM (legacy behavior)
  const shouldCallExternalAPIs = !assistant.isTesting() || process.env.TEST_EXTENDED_MODE;

  if (!shouldCallExternalAPIs) {
    assistant.log('email-preferences (anon): Skipping SendGrid (BEM_TESTING=true)');
    return assistant.respond({ success: true });
  }

  try {
    if (action === 'unsubscribe') {
      // POST returns JSON ({recipient_emails: [...]}) on success
      await fetch(`https://api.sendgrid.com/v3/asm/groups/${asmId}/suppressions`, {
        method: 'POST',
        response: 'json',
        headers: { 'Authorization': `Bearer ${process.env.SENDGRID_API_KEY}` },
        timeout: 60000,
        body: { recipient_emails: [email] },
      });
    } else {
      // DELETE returns 204 with empty body — must NOT request response: 'json'
      // or wonderful-fetch throws SyntaxError on the empty body.
      await fetch(`https://api.sendgrid.com/v3/asm/groups/${asmId}/suppressions/${encodeURIComponent(email)}`, {
        method: 'DELETE',
        response: 'text',
        headers: { 'Authorization': `Bearer ${process.env.SENDGRID_API_KEY}` },
        timeout: 60000,
      });
    }
  } catch (e) {
    assistant.log(`SendGrid ASM ${action} error:`, e);
    return assistant.respond('Failed to process your request', { code: 500 });
  }

  assistant.log('email-preferences (anon) result:', { email, asmId, action });
  analytics.event('marketing/email-preferences', { action, mode: 'anonymous' });

  return assistant.respond({ success: true });
}

/**
 * Anonymous HMAC unsub also writes to the user doc (if found) so consent stays in sync.
 * Silent if the email doesn't map to a user. Source is recorded as 'sendgrid' since the
 * HMAC link only fires from SendGrid email footers.
 */
async function mirrorAnonymousToUserDoc({ assistant, Manager, email, action }) {
  const { admin } = Manager.libraries;

  const snapshot = await admin.firestore().collection('users')
    .where('auth.email', '==', email)
    .limit(1)
    .get()
    .catch((e) => {
      assistant.error('email-preferences (anon): Failed to look up user by email:', e);
      return null;
    });

  if (!snapshot || snapshot.empty) {
    return; // Silent — email may not map to a current user
  }

  const userDoc = snapshot.docs[0];
  const uid = userDoc.id;
  const timestamp = assistant.meta.startTime.timestamp;
  const timestampUNIX = assistant.meta.startTime.timestampUNIX;

  const marketingPatch = action === 'unsubscribe'
    ? {
      status: 'revoked',
      revokedAt: { timestamp, timestampUNIX, source: 'sendgrid', ip: null, text: null },
    }
    : {
      status: 'granted',
      grantedAt: { timestamp, timestampUNIX, source: 'sendgrid', ip: null, text: null },
    };

  await admin.firestore().doc(`users/${uid}`).set({
    consent: { marketing: marketingPatch },
    metadata: Manager.Metadata().set({ tag: 'marketing/email-preferences' }),
  }, { merge: true })
    .catch((e) => {
      assistant.error(`email-preferences (anon): Failed to mirror to user doc ${uid}:`, e);
    });
}
