/**
 * POST /marketing/email-preferences - Update email preferences
 * Public endpoint — no authentication required
 *
 * Supports two actions:
 * - "unsubscribe": Adds email to SendGrid ASM suppression group
 * - "resubscribe": Removes email from SendGrid ASM suppression group
 */
const fetch = require('wonderful-fetch');
const crypto = require('crypto');

const RATE_LIMIT = 5;

module.exports = async ({ assistant, Manager, settings, analytics }) => {

  // Extract parameters
  const email = (settings.email || '').trim().toLowerCase();
  const asmId = parseInt(settings.asmId, 10);
  const action = settings.action || 'unsubscribe';

  // Validate email
  if (!email) {
    return assistant.respond('Email is required', { code: 400 });
  }

  const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
  if (!emailRegex.test(email)) {
    return assistant.respond('Invalid email format', { code: 400 });
  }

  // Validate ASM group ID
  if (!asmId || isNaN(asmId)) {
    return assistant.respond('ASM group ID is required', { code: 400 });
  }

  // Validate action
  if (action !== 'unsubscribe' && action !== 'resubscribe') {
    return assistant.respond('Invalid action', { code: 400 });
  }

  // Verify HMAC signature (proves the link was generated by our server)
  const expectedSig = crypto.createHmac('sha256', process.env.UNSUBSCRIBE_HMAC_KEY).update(email).digest('hex');
  if (settings.sig !== expectedSig) {
    return assistant.respond('Invalid signature', { code: 403 });
  }

  // Initialize Usage for rate limiting (key: IP forces unauthenticated storage always)
  const usage = await Manager.Usage().init(assistant, {
    unauthenticatedMode: 'firestore',
    key: assistant.request.geolocation.ip,
  });

  // Rate limiting (manual check since email-preferences isn't in product limits)
  const currentUsage = usage.getUsage('email-preferences');
  if (currentUsage >= RATE_LIMIT) {
    return assistant.respond('Rate limit exceeded', { code: 429 });
  }
  usage.increment('email-preferences');
  await usage.update();

  // Skip external API calls in test mode unless TEST_EXTENDED_MODE is set
  const shouldCallExternalAPIs = !assistant.isTesting() || process.env.TEST_EXTENDED_MODE;

  if (!shouldCallExternalAPIs) {
    assistant.log('marketing/email-preferences: Skipping SendGrid (BEM_TESTING=true, TEST_EXTENDED_MODE not set)');
    return assistant.respond({ success: true });
  }

  // Call SendGrid ASM API
  try {
    if (action === 'unsubscribe') {
      // Add email to suppression group
      await fetch(`https://api.sendgrid.com/v3/asm/groups/${asmId}/suppressions`, {
        method: 'POST',
        response: 'json',
        headers: {
          'Authorization': `Bearer ${process.env.SENDGRID_API_KEY}`,
        },
        timeout: 10000,
        body: {
          recipient_emails: [email],
        },
      });
    } else {
      // Remove email from suppression group
      await fetch(`https://api.sendgrid.com/v3/asm/groups/${asmId}/suppressions/${encodeURIComponent(email)}`, {
        method: 'DELETE',
        response: 'json',
        headers: {
          'Authorization': `Bearer ${process.env.SENDGRID_API_KEY}`,
        },
        timeout: 10000,
      });
    }
  } catch (e) {
    assistant.log(`SendGrid ASM ${action} error:`, e);
    return assistant.respond('Failed to process your request', { code: 500 });
  }

  // Log result
  assistant.log('marketing/email-preferences result:', { email, asmId, action });

  // Track analytics
  analytics.event('marketing/email-preferences', { action });

  // Generic success (no sensitive info leakage)
  return assistant.respond({ success: true });
};
