module.exports = {
  BaseCommand: require('./base-command'),
  VersionCommand: require('./version'),
  ClearCommand: require('./clear'),
  CwdCommand: require('./cwd'),
  SetupCommand: require('./setup'),
  InstallCommand: require('./install'),
  ServeCommand: require('./serve'),
  DeployCommand: require('./deploy'),
  TestCommand: require('./test'),
  EmulatorsCommand: require('./emulators'),
  CleanCommand: require('./clean'),
  IndexesCommand: require('./indexes'),
  WatchCommand: require('./watch'),
};